version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    build: ./eureka-server
    container_name: eureka
    ports:
      - "8001:8001"
    depends_on:
      - mysql

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8010:8010"
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8005:8005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/taskdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - mysql
      - eureka-server

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - mysql
      - eureka-server

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8006:8006"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payments
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - mysql
      - eureka-server

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cartdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - mysql
      - eureka-server

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8004:8004"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8001/eureka
    depends_on:
      - mysql
      - eureka-server

volumes:
  mysql_data: